---
title: "Estimated accuracy"
output: html_notebook
---


```{r}
library(tidyverse)
ss <- read.csv("../data_clean/2023-01-28_participants_clean_an-exp1_n-91.csv")
ts_p <- read.csv("../data_clean/2023-01-28_test_prediction_clean_an-exp1_n-91.csv")
ts_c <- read.csv("../data_clean/2023-01-28_test_control_clean_an-exp1_n-91.csv")
ts_e <- read.csv("../data_clean/2023-01-28_test_explanation_clean_an-exp1_n-91.csv")
```

```{r}
tmp_p <- ts_p %>% select(participant_id, fsm_type, trial_type, response_correct, response, correct_response = prediction_correct, trial_id) %>% mutate(task = "Prediction")
tmp_c <- ts_c %>% select(participant_id, fsm_type, trial_type, response_correct, trial_id) %>% mutate(task = "Control")
tmp_e <- ts_e %>% select(participant_id, fsm_type, trial_type, response_correct, trial_id) %>% mutate(task = "Explanation")

ts <- tmp_p %>% bind_rows(tmp_c) %>% bind_rows(tmp_e)
```

```{r}
tmp <- ts %>% group_by(participant_id, trial_type, fsm_type, task) %>% summarise(accuracy_m = mean(response_correct, na.rm = T)) %>% 
  mutate(trial_type = as.factor(trial_type), 
         fsm_type = as.factor(fsm_type), 
         task = as.factor(task)) %>% 
  mutate(trial_type = fct_rev(trial_type),
         fsm_type = fct_rev(fsm_type), 
         task = fct_relevel(task, c("Prediction", "Explanation", "Control")))

ggplot(tmp, aes(trial_type, accuracy_m)) + 
  geom_boxplot() + 
  geom_point(position = position_jitter(0.2, seed = 1), alpha = 0.1, size = 2)+
  geom_hline(yintercept=0.5,color="red", linetype = "dotted") + 
  facet_grid(fsm_type~task) + theme_classic()
```

Actual vs. estimated performace
```{r}
tmp_est <- ss %>% select(participant_id, q_estimate)
tmp_acc <- ts %>% group_by(participant_id, task, fsm_type) %>% summarise(accuracy_sum = sum(response_correct))
tmp_ss_acc <- tmp_acc %>% left_join(tmp_est)
ggplot(tmp_ss_acc, aes(as.factor(q_estimate), accuracy_sum, color = fsm_type)) + 
  geom_boxplot()
```


